### ISSUE TITLE
fix for A1200 Rev 2B Amiga RMB

### ISSUE THREAD

**Issue by kipper2k** [simoninns/SmallyMouse2#23] opened 2021-06-10 12:25 UTC
After building and testing the smally mouse on Amigas i found that the Rev2B A1200 Amiga RMB did not work. the problem was identified as bad caps and non working Paula. There is someone on Ebay who is selling "fixed" adapters but as far as i can tell he has not released any details on how he done it.

 I believe i have fixed the problem by placing 2 mosfets in cascade from the chip to the RMB input. I will play around with the resistor values and do a little more testing and then i will release the mod here so all can benefit

**Comment by Sgw32** [comment] 2022-10-12 17:06
@kipper2k Thanks for the idea!
Does it work on Amiga 500?

**Comment by kipper2k** [comment] 2022-10-12 19:53
yah, works on all

**Comment by kipper2k** [comment] 2023-07-18 13:42
Forgot to add this, it is a render of how it looks on the motherboard.
There is a USB header so people can run a USB cable if they don't want to
use the actual USB plug,. below the Smally is my video Hybrid board which
you break off and an expansion board for IDE so people can mount it
wherever :)

Brian

**Comment by simoninns** [comment] 2023-11-20 15:50
Closing issue as this is not a bug (hopefully the closed issue will still be searchable if there are people with similar problems).

**Closed as completed by simoninns** 2023-11-20 15:50 UTC
